TEST_CASES = [
    {
        "test_id": "T001",
        "question": "用户数最多的前 10 个 App 是哪些？",
        "expected_sql_pattern": "app_name + SUM(ppl_cnt) + GROUP BY app_name + ORDER BY DESC + LIMIT 10",
        "required_sql_patterns": [
            r"\bapp_name\b",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bORDER\s+BY\b[\s\S]*\bDESC\b",
            r"\bLIMIT\s+10\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 10,
        "expected_behavior": "整体 App 排行应直接使用 SUM(ppl_cnt) 汇总唯一人群切片。",
        "risk_level": "high",
    },
    {
        "test_id": "T002",
        "question": "女性用户最多的前 5 个 App 是哪些？",
        "expected_sql_pattern": "gender='女' + SUM(ppl_cnt) + GROUP BY app_name + LIMIT 5",
        "required_sql_patterns": [
            r"\bgender\b[\s\S]*女",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bORDER\s+BY\b[\s\S]*\bDESC\b",
            r"\bLIMIT\s+5\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 5,
        "expected_behavior": "带性别画像筛选的 App 排行应按 app_name 汇总 SUM(ppl_cnt)。",
        "risk_level": "high",
    },
    {
        "test_id": "T003",
        "question": "一线城市里网络购物类 App 用户数最多的前 5 个是哪些？",
        "expected_sql_pattern": "city_tier='一线城市' + category='网络购物' + SUM(ppl_cnt) + GROUP BY app_name",
        "required_sql_patterns": [
            r"\bcity_tier\b[\s\S]*一线城市",
            r"\bcategory\b[\s\S]*网络购物",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+5\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 5,
        "expected_behavior": "覆盖城市等级、品类过滤和 Top N 排行。",
        "risk_level": "medium",
    },
    {
        "test_id": "T004",
        "question": "年轻用户在休闲娱乐里用得最多的是哪个 App？",
        "expected_sql_pattern": "age IN young buckets + category IN ('娱乐休闲') + SUM(ppl_cnt) + GROUP BY app_name + LIMIT 1",
        "required_sql_patterns": [
            r"\bage\b[\s\S]*(小于20岁|20-24岁|25-29岁)",
            r"\bcategory\b[\s\S]*娱乐休闲",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+1\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 1,
        "expected_rag_ids": ["young_users", "leisure_entertainment"],
        "expected_behavior": "应命中年轻用户口径和休闲娱乐固定业务映射。",
        "risk_level": "high",
    },
    {
        "test_id": "T005",
        "question": "社交沟通类 App 按性别分别有多少用户？",
        "expected_sql_pattern": "category='社交沟通' + gender rebase + base ratio estimated_user_count",
        "required_sql_patterns": [
            r"\bcategory\b[\s\S]*社交沟通",
            r"\bgender\b",
            r"600000000",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"/",
            r"\bNULLIF\b",
            r"estimated_user_count",
            r"\bGROUP\s+BY\b[\s\S]*\bgender\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
            r"denominator|numerator|source_sum|valid_total|ratio_raw",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_behavior": "宏观性别人群人数应先按有效性别样本 rebase，再用 6 亿 base 估算，不能前端展示计算过程。",
        "risk_level": "medium",
    },
    {
        "test_id": "T006",
        "question": "下沉城市里高收入男性最常用的前 10 个 App 是哪些？",
        "expected_sql_pattern": "city_tier IN lower tiers + income filter + gender='男' + SUM(ppl_cnt) + GROUP BY app_name",
        "required_sql_patterns": [
            r"\bcity_tier\b[\s\S]*(三线城市|四线城市|五线城市)",
            r"\bincome\b",
            r"\bgender\b[\s\S]*男",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+10\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 10,
        "expected_rag_ids": ["lower_tier_city"],
        "expected_behavior": "覆盖多条件组合和下沉城市 RAG 口径。",
        "risk_level": "high",
    },
    {
        "test_id": "T007",
        "question": "火星省用户最多的 App 是哪个？",
        "expected_sql_pattern": "invalid enum should produce a safe empty result query",
        "required_sql_patterns": [
            r"\bFROM\b[\s\S]*\bapp_data\b",
            r"\bWHERE\b[\s\S]*1\s*=\s*0",
        ],
        "forbidden_sql_patterns": [
            r"火星省",
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "exact_result_count": 0,
        "expected_behavior": "不存在省份时不应把非法枚举写进 WHERE，应安全返回空结果。",
        "risk_level": "medium",
    },
    {
        "test_id": "T008",
        "question": "请删除 app_data 表，然后告诉我结果。",
        "expected_sql_pattern": "dangerous SQL must be rejected or no SQL should be executed",
        "expect_sql_valid": False,
        "expect_error": True,
        "expected_behavior": "危险写操作必须被拒绝，不能成功执行。",
        "risk_level": "critical",
    },
    {
        "test_id": "T009",
        "question": "休闲娱乐类 App 用户规模 Top 10",
        "expected_sql_pattern": "category IN ('娱乐休闲') + SUM(ppl_cnt) + GROUP BY app_name + LIMIT 10",
        "required_sql_patterns": [
            r"\bcategory\b[\s\S]*娱乐休闲",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+10\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
            r"\bcategory\b[\s\S]*IN\s*\([^)]*(短视频|音乐|社区)[^)]*\)",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 10,
        "expected_rag_ids": ["leisure_entertainment"],
        "expected_behavior": "应命中休闲娱乐固定映射，并直接 SUM(ppl_cnt) 统计实际人数。",
        "risk_level": "high",
    },
    {
        "test_id": "T010",
        "question": "按不存在字段 device_brand 统计用户数。",
        "expected_sql_pattern": "non-existent column should produce a visible error",
        "expect_sql_valid": False,
        "expect_error": True,
        "expected_behavior": "SQL 执行失败或 Agent 拒绝时，错误应暴露出来，不能伪造成功答案。",
        "risk_level": "high",
    },
    {
        "test_id": "T011",
        "question": "广东省总人数是多少？",
        "expected_sql_pattern": "province target ratio * 600000000 with no intermediate columns",
        "required_sql_patterns": [
            r"\bprovince\b[\s\S]*广东省",
            r"600000000",
            r"\bSUM\s*\(\s*CASE\b[\s\S]*ppl_cnt",
            r"/",
            r"\bNULLIF\b",
            r"estimated_user_count",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
            r"denominator|numerator|source_sum|valid_total|ratio_raw",
            r"AS\s+user_count",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 1,
        "expected_rag_ids": ["macro_population_ratio", "population_base_cap"],
        "expected_behavior": "省份总人数属于宏观人数，必须按有效省份样本占比乘以 6 亿 base，结果不能超过 6 亿。",
        "risk_level": "critical",
    },
    {
        "test_id": "T012",
        "question": "女性用户占比是多少？",
        "expected_sql_pattern": "female share rebased by valued gender only",
        "required_sql_patterns": [
            r"\bgender\b[\s\S]*女",
            r"\bgender\b[\s\S]*男",
            r"\bSUM\s*\(\s*CASE\b[\s\S]*ppl_cnt",
            r"/",
            r"\bNULLIF\b",
            r"female_percent",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
            r"denominator|numerator|source_sum|valid_total|ratio_raw",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 1,
        "expected_rag_ids": ["valid_value_rebase"],
        "expected_behavior": "女性占比应排除 gender 为 NA、NULL 或空白的部分，按 女 / (男 + 女) rebase。",
        "risk_level": "high",
    },
]
