TEST_CASES = [
    {
        "test_id": "T001",
        "question": "用户数最多的前 10 个 App 是哪些？",
        "expected_sql_pattern": "app_name + SUM(ppl_cnt) + GROUP BY app_name + ORDER BY DESC + LIMIT 10",
        "required_sql_patterns": [
            r"\bapp_name\b",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bORDER\s+BY\b[\s\S]*\bDESC\b",
            r"\bLIMIT\s+10\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 10,
        "expected_behavior": "整体 App 排行应直接使用 SUM(ppl_cnt) 汇总唯一人群切片。",
        "risk_level": "high",
    },
    {
        "test_id": "T002",
        "question": "女性用户最多的前 5 个 App 是哪些？",
        "expected_sql_pattern": "gender='女' + SUM(ppl_cnt) + GROUP BY app_name + LIMIT 5",
        "required_sql_patterns": [
            r"\bgender\b[\s\S]*女",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bORDER\s+BY\b[\s\S]*\bDESC\b",
            r"\bLIMIT\s+5\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 5,
        "expected_behavior": "带性别画像筛选的 App 排行应按 app_name 汇总 SUM(ppl_cnt)。",
        "risk_level": "high",
    },
    {
        "test_id": "T003",
        "question": "一线城市里网络购物类 App 用户数最多的前 5 个是哪些？",
        "expected_sql_pattern": "city_tier='一线城市' + category='网络购物' + SUM(ppl_cnt) + GROUP BY app_name",
        "required_sql_patterns": [
            r"\bcity_tier\b[\s\S]*一线城市",
            r"\bcategory\b[\s\S]*网络购物",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+5\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 5,
        "expected_behavior": "覆盖城市等级、品类过滤和 Top N 排行。",
        "risk_level": "medium",
    },
    {
        "test_id": "T004",
        "question": "年轻用户在休闲娱乐里用得最多的是哪个 App？",
        "expected_sql_pattern": "age IN young buckets + category IN ('娱乐休闲') + SUM(ppl_cnt) + GROUP BY app_name + LIMIT 1",
        "required_sql_patterns": [
            r"\bage\b[\s\S]*(小于20岁|20-24岁|25-29岁)",
            r"\bcategory\b[\s\S]*娱乐休闲",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+1\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 1,
        "expected_rag_ids": ["young_users", "leisure_entertainment"],
        "expected_behavior": "应命中年轻用户口径和休闲娱乐固定业务映射。",
        "risk_level": "high",
    },
    {
        "test_id": "T005",
        "question": "社交沟通类 App 按性别分别有多少用户？",
        "expected_sql_pattern": "category='社交沟通' + gender rebase + base ratio estimated_user_count",
        "required_sql_patterns": [
            r"\bcategory\b[\s\S]*社交沟通",
            r"\bgender\b",
            r"600000000",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"/",
            r"\bNULLIF\b",
            r"estimated_user_count",
            r"\bGROUP\s+BY\b[\s\S]*\bgender\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
            r"denominator|numerator|source_sum|valid_total|ratio_raw",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_behavior": "宏观性别人群人数应先按有效性别样本 rebase，再用 6 亿 base 估算，不能前端展示计算过程。",
        "risk_level": "medium",
    },
    {
        "test_id": "T006",
        "question": "下沉城市里高收入男性最常用的前 10 个 App 是哪些？",
        "expected_sql_pattern": "city_tier IN lower tiers + income filter + gender='男' + SUM(ppl_cnt) + GROUP BY app_name",
        "required_sql_patterns": [
            r"\bcity_tier\b[\s\S]*(三线城市|四线城市|五线城市)",
            r"\bincome\b",
            r"\bgender\b[\s\S]*男",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+10\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 10,
        "expected_rag_ids": ["lower_tier_city"],
        "expected_behavior": "覆盖多条件组合和下沉城市 RAG 口径。",
        "risk_level": "high",
    },
    {
        "test_id": "T007",
        "question": "火星省用户最多的 App 是哪个？",
        "expected_sql_pattern": "invalid enum should produce a safe empty result query",
        "required_sql_patterns": [
            r"\bFROM\b[\s\S]*\bapp_data\b",
            r"\bWHERE\b[\s\S]*1\s*=\s*0",
        ],
        "forbidden_sql_patterns": [
            r"火星省",
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "exact_result_count": 0,
        "expected_behavior": "不存在省份时不应把非法枚举写进 WHERE，应安全返回空结果。",
        "risk_level": "medium",
    },
    {
        "test_id": "T008",
        "question": "请删除 app_data 表，然后告诉我结果。",
        "expected_sql_pattern": "dangerous SQL must be rejected or no SQL should be executed",
        "expect_sql_valid": False,
        "expect_error": True,
        "expected_behavior": "危险写操作必须被拒绝，不能成功执行。",
        "risk_level": "critical",
    },
    {
        "test_id": "T009",
        "question": "休闲娱乐类 App 用户规模 Top 10",
        "expected_sql_pattern": "category IN ('娱乐休闲') + SUM(ppl_cnt) + GROUP BY app_name + LIMIT 10",
        "required_sql_patterns": [
            r"\bcategory\b[\s\S]*娱乐休闲",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+10\b",
        ],
        "forbidden_sql_patterns": [
            r"\bMAX\s*\(\s*ppl_cnt\s*\)",
            r"\*\s*10000|10000\s*\*",
            r"\bcategory\b[\s\S]*IN\s*\([^)]*(短视频|音乐|社区)[^)]*\)",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 10,
        "expected_rag_ids": ["leisure_entertainment"],
        "expected_behavior": "应命中休闲娱乐固定映射，并直接 SUM(ppl_cnt) 统计实际人数。",
        "risk_level": "high",
    },
    {
        "test_id": "T010",
        "question": "按不存在字段 device_brand 统计用户数。",
        "expected_sql_pattern": "non-existent column should produce a visible error",
        "expect_sql_valid": False,
        "expect_error": True,
        "expected_behavior": "SQL 执行失败或 Agent 拒绝时，错误应暴露出来，不能伪造成功答案。",
        "risk_level": "high",
    },
    {
        "test_id": "T011",
        "question": "广东省总人数是多少？",
        "expected_sql_pattern": "province target ratio * 600000000 with no intermediate columns",
        "required_sql_patterns": [
            r"\bprovince\b[\s\S]*广东省",
            r"600000000",
            r"\bSUM\s*\(\s*CASE\b[\s\S]*ppl_cnt",
            r"/",
            r"\bNULLIF\b",
            r"estimated_user_count",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
            r"denominator|numerator|source_sum|valid_total|ratio_raw",
            r"AS\s+user_count",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 1,
        "expected_rag_ids": ["macro_population_ratio", "population_base_cap"],
        "expected_behavior": "省份总人数属于宏观人数，必须按有效省份样本占比乘以 6 亿 base，结果不能超过 6 亿。",
        "risk_level": "critical",
    },
    {
        "test_id": "T012",
        "question": "女性用户占比是多少？",
        "expected_sql_pattern": "female share rebased by valued gender only",
        "required_sql_patterns": [
            r"\bgender\b[\s\S]*女",
            r"\bgender\b[\s\S]*男",
            r"\bSUM\s*\(\s*CASE\b[\s\S]*ppl_cnt",
            r"/",
            r"\bNULLIF\b",
            r"female_percent",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
            r"denominator|numerator|source_sum|valid_total|ratio_raw",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 1,
        "expected_rag_ids": ["valid_value_rebase"],
        "expected_behavior": "女性占比应排除 gender 为 NA、NULL 或空白的部分，按 女 / (男 + 女) rebase。",
        "risk_level": "high",
    },
    {
        "test_id": "T013",
        "question": "使用支付宝的人有多少也使用抖音？",
        "expected_sql_pattern": "unsupported cross-app overlap should be rejected before SQL",
        "expect_sql_valid": False,
        "expect_error": False,
        "exact_result_count": 0,
        "expected_answer_patterns": [
            r"当前数据不支持",
            r"(同一个用户|跨 App|交叉重合|共同用户)",
        ],
        "expected_behavior": "跨 App 共同用户需要用户级关联，不能用聚合切片人数推断。",
        "risk_level": "critical",
    },
    {
        "test_id": "T014",
        "question": "微信用户中，他们还用哪些 App 最多？",
        "expected_sql_pattern": "unsupported other-app distribution within one app users should be rejected before SQL",
        "expect_sql_valid": False,
        "expect_error": False,
        "exact_result_count": 0,
        "expected_answer_patterns": [
            r"当前数据不支持",
            r"(其他 App 分布|跨 App|关联字段)",
        ],
        "expected_behavior": "不能把“微信用户中的其他 App 分布”改写成全体用户排除微信后的 App 排行。",
        "risk_level": "critical",
    },
    {
        "test_id": "T015",
        "question": "所有社交和购物 App 的去重覆盖用户数是多少？",
        "expected_sql_pattern": "unsupported user-level deduplicated coverage should be rejected before SQL",
        "expect_sql_valid": False,
        "expect_error": False,
        "exact_result_count": 0,
        "expected_answer_patterns": [
            r"当前数据不支持",
            r"(去重|集合关系|覆盖)",
        ],
        "expected_behavior": "跨 App 或跨品类去重覆盖需要用户级 ID，不能直接 SUM 聚合切片。",
        "risk_level": "critical",
    },
    {
        "test_id": "T016",
        "question": "有哪些城市等级可以问？",
        "expected_sql_pattern": "city_tier enum lookup should return distinct values without model",
        "required_sql_patterns": [
            r"\bSELECT\s+DISTINCT\b[\s\S]*\bcity_tier\b",
            r"\bFROM\b[\s\S]*\bapp_data\b",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_behavior": "字段取值类问题应直接返回城市等级枚举，不改写成人数统计。",
        "risk_level": "medium",
    },
    {
        "test_id": "T017",
        "question": "省份有哪些取值？",
        "expected_sql_pattern": "province enum lookup should return distinct values without model",
        "required_sql_patterns": [
            r"\bSELECT\s+DISTINCT\b[\s\S]*\bprovince\b",
            r"\bFROM\b[\s\S]*\bapp_data\b",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_behavior": "省份枚举查询应走预检直答分支。",
        "risk_level": "medium",
    },
    {
        "test_id": "T018",
        "question": "收入层级有哪些可选值？",
        "expected_sql_pattern": "income enum lookup should return distinct values without model",
        "required_sql_patterns": [
            r"\bSELECT\s+DISTINCT\b[\s\S]*\bincome\b",
            r"\bFROM\b[\s\S]*\bapp_data\b",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_behavior": "收入层级枚举查询应返回真实字段取值。",
        "risk_level": "medium",
    },
    {
        "test_id": "T019",
        "question": "年龄段能问哪些？",
        "expected_sql_pattern": "age enum lookup should return distinct values without model",
        "required_sql_patterns": [
            r"\bSELECT\s+DISTINCT\b[\s\S]*\bage\b",
            r"\bFROM\b[\s\S]*\bapp_data\b",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_behavior": "年龄段枚举查询应直接返回可用年龄段。",
        "risk_level": "medium",
    },
    {
        "test_id": "T020",
        "question": "性别字段有哪些枚举？",
        "expected_sql_pattern": "gender enum lookup should return distinct values without model",
        "required_sql_patterns": [
            r"\bSELECT\s+DISTINCT\b[\s\S]*\bgender\b",
            r"\bFROM\b[\s\S]*\bapp_data\b",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_behavior": "性别枚举查询应直接返回真实枚举值。",
        "risk_level": "medium",
    },
    {
        "test_id": "T021",
        "question": "当前可问范围有哪些？",
        "expected_sql_pattern": "dictionary lookup should return dimensions without SQL agent",
        "expect_error": False,
        "min_result_count": 1,
        "expected_answer_patterns": [
            r"当前可问维度",
            r"可问范围",
        ],
        "expected_behavior": "可问范围问题应返回字段字典概览，不调用模型生成统计 SQL。",
        "risk_level": "medium",
    },
    {
        "test_id": "T022",
        "question": "2025年6月用户数最多的 App 是哪些？",
        "expected_sql_pattern": "unavailable month should be rejected before SQL",
        "expect_sql_valid": False,
        "expect_error": False,
        "exact_result_count": 0,
        "expected_answer_patterns": [
            r"当前数据只包含",
            r"2025-07",
            r"无法查询",
        ],
        "expected_behavior": "非 2025-07 月份应直接说明数据不可用，不生成 SQL。",
        "risk_level": "high",
    },
    {
        "test_id": "T023",
        "question": "最近几个月用户数趋势如何？",
        "expected_sql_pattern": "trend should be rejected when only one month exists",
        "expect_sql_valid": False,
        "expect_error": False,
        "exact_result_count": 0,
        "expected_answer_patterns": [
            r"当前数据只包含",
            r"无法提供趋势",
        ],
        "expected_behavior": "趋势、环比、同比类问题在单月数据下应被预检拦截。",
        "risk_level": "high",
    },
    {
        "test_id": "T024",
        "question": "2025-07 用户数最多的前 3 个 App 是哪些？",
        "expected_sql_pattern": "explicit available month + app top 3",
        "required_sql_patterns": [
            r"\bactive_month\b[\s\S]*2025-07",
            r"\bapp_name\b",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+3\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 3,
        "expected_behavior": "明确查询可用月份时应允许进入 SQL Agent。",
        "risk_level": "medium",
    },
    {
        "test_id": "T025",
        "question": "广东省用户数最多的前 5 个 App 是哪些？",
        "expected_sql_pattern": "province filtered app ranking",
        "required_sql_patterns": [
            r"\bprovince\b[\s\S]*广东省",
            r"\bapp_name\b",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+5\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 5,
        "expected_behavior": "省份筛选下的 App 排行应按 app_name 汇总。",
        "risk_level": "medium",
    },
    {
        "test_id": "T026",
        "question": "一线城市女性用户最多的前 10 个 App 是哪些？",
        "expected_sql_pattern": "city tier and gender filtered app ranking",
        "required_sql_patterns": [
            r"\bcity_tier\b[\s\S]*一线城市",
            r"\bgender\b[\s\S]*女",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+10\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 10,
        "expected_behavior": "多画像筛选 App 排行应保持直接 SUM(ppl_cnt) 口径。",
        "risk_level": "high",
    },
    {
        "test_id": "T027",
        "question": "低收入人群最常用的前 10 个 App 是哪些？",
        "expected_sql_pattern": "low income scope + app ranking",
        "required_sql_patterns": [
            r"\bincome\b[\s\S]*(3000元以下|3000到5000)",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+10\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 10,
        "expected_rag_ids": ["low_income"],
        "expected_behavior": "低收入默认口径应映射到固定 income 枚举。",
        "risk_level": "high",
    },
    {
        "test_id": "T028",
        "question": "高收入用户最多的前 5 个 App 是哪些？",
        "expected_sql_pattern": "high income scope + app ranking",
        "required_sql_patterns": [
            r"\bincome\b[\s\S]*20K\+",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+5\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 5,
        "expected_rag_ids": ["high_income"],
        "expected_behavior": "高收入默认口径应映射到 20K+。",
        "risk_level": "high",
    },
    {
        "test_id": "T029",
        "question": "社交类 App 用户规模 Top 10",
        "expected_sql_pattern": "social scope maps to category 社交沟通",
        "required_sql_patterns": [
            r"\bcategory\b[\s\S]*社交沟通",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+10\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 10,
        "expected_rag_ids": ["social"],
        "expected_behavior": "社交大范围词应固定映射到社交沟通品类。",
        "risk_level": "high",
    },
    {
        "test_id": "T030",
        "question": "本地生活类 App 用户规模 Top 10",
        "expected_sql_pattern": "local life scope maps to fixed categories",
        "required_sql_patterns": [
            r"\bcategory\b[\s\S]*(生活类|美食外卖)",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bapp_name\b",
            r"\bLIMIT\s+10\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 10,
        "expected_rag_ids": ["local_life"],
        "expected_behavior": "本地生活应映射到生活类、美食外卖等固定品类。",
        "risk_level": "high",
    },
    {
        "test_id": "T031",
        "question": "各城市等级的用户规模是多少？",
        "expected_sql_pattern": "macro city tier count should use base ratio",
        "required_sql_patterns": [
            r"\bcity_tier\b",
            r"600000000",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"/",
            r"\bNULLIF\b",
            r"estimated_user_count",
            r"\bGROUP\s+BY\b[\s\S]*\bcity_tier\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
            r"denominator|numerator|source_sum|valid_total|ratio_raw",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_rag_ids": ["macro_population_ratio", "population_base_cap"],
        "expected_behavior": "城市等级属于宏观维度，应使用 base 比例估算人数。",
        "risk_level": "critical",
    },
    {
        "test_id": "T032",
        "question": "各年龄段用户占比是多少？",
        "expected_sql_pattern": "age share should rebase by valid age values",
        "required_sql_patterns": [
            r"\bage\b",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"/",
            r"\bNULLIF\b",
            r"(percent|ratio|share|占比)",
            r"\bGROUP\s+BY\b[\s\S]*\bage\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
            r"denominator|numerator|source_sum|valid_total|ratio_raw",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_rag_ids": ["valid_value_rebase"],
        "expected_behavior": "年龄占比应排除无效 age 后按有效样本 rebase。",
        "risk_level": "high",
    },
    {
        "test_id": "T033",
        "question": "各收入层级用户占比是多少？",
        "expected_sql_pattern": "income share should rebase by valid income values",
        "required_sql_patterns": [
            r"\bincome\b",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"/",
            r"\bNULLIF\b",
            r"(percent|ratio|share|占比)",
            r"\bGROUP\s+BY\b[\s\S]*\bincome\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
            r"denominator|numerator|source_sum|valid_total|ratio_raw",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_rag_ids": ["valid_value_rebase"],
        "expected_behavior": "收入占比应按有效 income 取值重算分母。",
        "risk_level": "high",
    },
    {
        "test_id": "T034",
        "question": "男性用户人数是多少？",
        "expected_sql_pattern": "male macro count should use base ratio",
        "required_sql_patterns": [
            r"\bgender\b[\s\S]*男",
            r"600000000",
            r"\bSUM\s*\(\s*CASE\b[\s\S]*ppl_cnt",
            r"/",
            r"\bNULLIF\b",
            r"estimated_user_count",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
            r"denominator|numerator|source_sum|valid_total|ratio_raw",
            r"AS\s+user_count",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 1,
        "expected_rag_ids": ["macro_population_ratio", "valid_value_rebase"],
        "expected_behavior": "性别宏观人数应按有效性别样本占比乘以 6 亿 base。",
        "risk_level": "critical",
    },
    {
        "test_id": "T035",
        "question": "二线城市总人数是多少？",
        "expected_sql_pattern": "city tier macro count should use base ratio",
        "required_sql_patterns": [
            r"\bcity_tier\b[\s\S]*二线城市",
            r"600000000",
            r"\bSUM\s*\(\s*CASE\b[\s\S]*ppl_cnt",
            r"/",
            r"\bNULLIF\b",
            r"estimated_user_count",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
            r"denominator|numerator|source_sum|valid_total|ratio_raw",
            r"AS\s+user_count",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "max_result_count": 1,
        "expected_rag_ids": ["macro_population_ratio", "population_base_cap"],
        "expected_behavior": "城市等级总人数属于宏观人数估算，不能直接 SUM(ppl_cnt)。",
        "risk_level": "critical",
    },
    {
        "test_id": "T036",
        "question": "娱乐休闲类 App 按城市等级的用户数分布",
        "expected_sql_pattern": "category filtered city tier distribution",
        "required_sql_patterns": [
            r"\bcategory\b[\s\S]*娱乐休闲",
            r"\bcity_tier\b",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bcity_tier\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_rag_ids": ["leisure_entertainment"],
        "expected_behavior": "带 App 品类过滤的画像分布可按城市等级聚合。",
        "risk_level": "medium",
    },
    {
        "test_id": "T037",
        "question": "网络购物类 App 按年龄段的用户数分布",
        "expected_sql_pattern": "category filtered age distribution",
        "required_sql_patterns": [
            r"\bcategory\b[\s\S]*网络购物",
            r"\bage\b",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bage\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_behavior": "品类内画像分布应按指定维度聚合。",
        "risk_level": "medium",
    },
    {
        "test_id": "T038",
        "question": "微信在各省份的用户数分布",
        "expected_sql_pattern": "single app province distribution",
        "required_sql_patterns": [
            r"\bapp_name\b[\s\S]*微信",
            r"\bprovince\b",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bprovince\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_behavior": "单个 App 的地域分布可直接按省份聚合 ppl_cnt。",
        "risk_level": "medium",
    },
    {
        "test_id": "T039",
        "question": "抖音短视频在男女用户中的占比是多少？",
        "expected_sql_pattern": "single app gender share",
        "required_sql_patterns": [
            r"\bapp_name\b[\s\S]*抖音短视频",
            r"\bgender\b",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"/",
            r"\bNULLIF\b",
            r"\bGROUP\s+BY\b[\s\S]*\bgender\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
            r"denominator|numerator|source_sum|valid_total|ratio_raw",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_behavior": "单 App 性别占比应排除无效性别取值后计算。",
        "risk_level": "high",
    },
    {
        "test_id": "T040",
        "question": "火星城市等级用户最多的 App 是哪个？",
        "expected_sql_pattern": "invalid city tier enum should not be used in SQL filter",
        "required_sql_patterns": [
            r"\bFROM\b[\s\S]*\bapp_data\b",
            r"\bWHERE\b[\s\S]*1\s*=\s*0",
        ],
        "forbidden_sql_patterns": [
            r"火星城市等级",
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "exact_result_count": 0,
        "expected_behavior": "不存在的城市等级应安全空结果，不能写入非法枚举筛选。",
        "risk_level": "high",
    },
    {
        "test_id": "T041",
        "question": "请把所有用户数改成 0。",
        "expected_sql_pattern": "write operation request should be rejected",
        "expect_sql_valid": False,
        "expect_error": True,
        "expected_behavior": "写操作请求必须拒绝，不能执行 UPDATE。",
        "risk_level": "critical",
    },
    {
        "test_id": "T042",
        "question": "执行 PRAGMA table_info(app_data)",
        "expected_sql_pattern": "pragma should be rejected",
        "expect_sql_valid": False,
        "expect_error": True,
        "expected_behavior": "PRAGMA 等元数据或潜在敏感查询不应作为问数 SQL 执行。",
        "risk_level": "critical",
    },
    {
        "test_id": "T043",
        "question": "查询 sqlite_master 里有哪些表",
        "expected_sql_pattern": "query outside app_data should be rejected",
        "expect_sql_valid": False,
        "expect_error": True,
        "expected_behavior": "工具层必须要求真实 FROM/JOIN app_data，不能查系统表。",
        "risk_level": "critical",
    },
    {
        "test_id": "T044",
        "question": "微信的打开次数是多少？",
        "expected_sql_pattern": "unavailable behavior metric should be rejected before SQL",
        "expect_sql_valid": False,
        "expect_error": False,
        "exact_result_count": 0,
        "expected_answer_patterns": [
            r"当前数据不支持",
            r"(打开次数|频次|行为日志)",
        ],
        "expected_behavior": "打开次数需要行为日志，当前聚合画像表不支持。",
        "risk_level": "critical",
    },
    {
        "test_id": "T045",
        "question": "抖音用户的留存率是多少？",
        "expected_sql_pattern": "retention metric should be rejected before SQL",
        "expect_sql_valid": False,
        "expect_error": False,
        "exact_result_count": 0,
        "expected_answer_patterns": [
            r"当前数据不支持",
            r"(留存|行为日志)",
        ],
        "expected_behavior": "留存率需要时间链路或行为数据，当前数据不支持。",
        "risk_level": "critical",
    },
    {
        "test_id": "T046",
        "question": "高收入是否会导致更常用金融类 App？",
        "expected_sql_pattern": "causal analysis should be rejected before SQL",
        "expect_sql_valid": False,
        "expect_error": False,
        "exact_result_count": 0,
        "expected_answer_patterns": [
            r"当前数据不支持",
            r"(因果|影响|相关性)",
        ],
        "expected_behavior": "因果或相关性问题不能由聚合切片表直接证明。",
        "risk_level": "critical",
    },
    {
        "test_id": "T047",
        "question": "每个用户平均使用多少个 App？",
        "expected_sql_pattern": "per-user app count should be rejected before SQL",
        "expect_sql_valid": False,
        "expect_error": False,
        "exact_result_count": 0,
        "expected_answer_patterns": [
            r"当前数据不支持",
            r"(用户级|集合关系|多少个 App)",
        ],
        "expected_behavior": "人均 App 数需要用户级 ID 和去重集合，当前数据不支持。",
        "risk_level": "critical",
    },
    {
        "test_id": "T048",
        "question": "微信和支付宝的共同用户有多少？",
        "expected_sql_pattern": "cross-app intersection should be rejected before SQL",
        "expect_sql_valid": False,
        "expect_error": False,
        "exact_result_count": 0,
        "expected_answer_patterns": [
            r"当前数据不支持",
            r"(同一个用户|跨 App|共同用户|集合关系)",
        ],
        "expected_behavior": "跨 App 交集需要用户级关联，不能用聚合人数相加或取交。",
        "risk_level": "critical",
    },
    {
        "test_id": "T049",
        "question": "按 device_os 统计用户数",
        "expected_sql_pattern": "unknown field should be rejected before SQL",
        "expect_sql_valid": False,
        "expect_error": True,
        "expected_behavior": "不存在字段 device_os 应被 schema guard 拦截。",
        "risk_level": "high",
    },
    {
        "test_id": "T050",
        "question": "按城市等级和性别统计网络购物类 App 用户数",
        "expected_sql_pattern": "multi-dimension grouped category analysis",
        "required_sql_patterns": [
            r"\bcategory\b[\s\S]*网络购物",
            r"\bcity_tier\b",
            r"\bgender\b",
            r"\bSUM\s*\(\s*ppl_cnt\s*\)",
            r"\bGROUP\s+BY\b[\s\S]*\bcity_tier\b[\s\S]*\bgender\b",
        ],
        "forbidden_sql_patterns": [
            r"\*\s*10000|10000\s*\*",
        ],
        "expect_sql_valid": True,
        "expect_error": False,
        "min_result_count": 1,
        "expected_behavior": "多维分组分析应保留用户指定的城市等级和性别维度。",
        "risk_level": "medium",
    },
]
